name: Build & Push Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: video2lm

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase owner
        id: vars
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.owner_lc }}/${{ env.IMAGE_PREFIX }}-api:latest
            ${{ env.REGISTRY }}/${{ env.owner_lc }}/${{ env.IMAGE_PREFIX }}-api:${{ github.sha }}

      - name: Build & push Worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.owner_lc }}/${{ env.IMAGE_PREFIX }}-worker:latest
            ${{ env.REGISTRY }}/${{ env.owner_lc }}/${{ env.IMAGE_PREFIX }}-worker:${{ github.sha }}

      - name: Build & push Web
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.owner_lc }}/${{ env.IMAGE_PREFIX }}-web:latest
            ${{ env.REGISTRY }}/${{ env.owner_lc }}/${{ env.IMAGE_PREFIX }}-web:${{ github.sha }}
